image: docker:stable

services:
  - docker:dind

variables:
  BUILDX_VERSION: v0.5.1
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
  PLATFORMS: linux/amd64,linux/arm64

stages:
  - build

build:
  stage: build
  only:
    - master
  before_script:
    - docker version
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -vp ~/.docker/cli-plugins/ ~/dockercache
    - wget "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64" -O ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker buildx build --platform $PLATFORMS --push -t $IMAGE_LATEST .
